config/routes.rb
MmoirpgServer::Application.routes.draw do
  devise_for :players

  resources :characters

  resources :battles do
    collection do
      get 'start'
    end
  end

  root 'characters#index'

  

end

app/models/battle.rb
class Battle < ActiveRecord::Base

  has_many :character_battles, dependent: :destroy

  def self.start
    battle = self.create

    characters = Character.all
    characters.shuffle

    while characters.size >= 2
      character_1 = characters.shift
      character_2 = characters.shift
      CharacterBattle.create( battle: battle, winner: character_1, loser: character_2)
    end

  end

end

# == Schema Information
#
# Table name: battles
#
#  id         :integer          not null, primary key
#  created_at :datetime
#  updated_at :datetime
#

app/models/character.rb
class Character < ActiveRecord::Base

  has_many :character_battles, dependent: :destroy
end

# == Schema Information
#
# Table name: characters
#
#  id         :integer          not null, primary key
#  player_id  :integer
#  name       :string(255)
#  strength   :integer
#  vitality   :integer
#  created_at :datetime
#  updated_at :datetime
#

app/models/character_battle.rb
class CharacterBattle < ActiveRecord::Base

  belongs_to :battle

  belongs_to :winner, class_name: "Character"
  belongs_to :loser, class_name: "Character"

  delegate :name, to: :loser, allow_nil: true, prefix: true
  delegate :name, to: :winner, allow_nil: true, prefix: true

end

# == Schema Information
#
# Table name: character_battles
#
#  id           :integer          not null, primary key
#  winner_id_id :integer
#  loser_id_id  :integer
#  battle_id    :integer
#  created_at   :datetime
#  updated_at   :datetime
#

app/models/player.rb
class Player < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

# == Schema Information
#
# Table name: players
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

app/models/player_battle.rb
class PlayerBattle < ActiveRecord::Base

end

# == Schema Information
#
# Table name: player_battles
#
#  id           :integer          not null, primary key
#  character_id :integer
#  battle_id    :integer
#  created_at   :datetime
#  updated_at   :datetime
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController

  def index
    @battles = Battle.all.decorate
  end

  def start
    Battle.start
    redirect_to battles_path
  end

  def show
    @battle = Battle.find params[:id]
  end

  def destroy
    @battle = Battle.find params[:id]
    @battle.destroy

    redirect_to battles_path
  end

end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  before_filter :authenticate_player!

  def index
    @characters = Character.all
  end

  def new
    @character = Character.new
  end

  def create
    Character.create(character_params)
    redirect_to characters_url
  end

  def destroy
    @character = Character.find(params[:id])
    @character.destroy
    redirect_to characters_url
  end

  private

  def character_params
    params[:character].permit([:name, :strength, :vitality])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/battles/index.haml
%h2 Battles

%p
  = link_to "Start battle", start_battles_path, class: 'btn btn-primary'

%p
  %table.table
    %tr
      %th ID
      %th Started
      %th Match count
      %th
    - @battles.each do |battle|
      %tr
        %td= battle.id
        %td= link_to battle.created_at, battle
        %td= battle.character_battles.count
        %td= link_to "delete", battle, method: :delete, confirm: 'Delete?'

app/views/battles/show.haml
%h1 Result

%table.table
  %tr
    %th Id
    %th Win
    %th Loss
  - @battle.character_battles.decorate.each do |cb|
    %tr
      %td= cb.id
      %td= cb.winner_name
      %td= cb.loser_name

app/views/characters/index.html.haml
%h1 Characters

%p
  = link_to "Create a new Character", new_character_path, class: 'btn btn-primary'

%p
  %table.table
    %tr
      %th Id
      %th Name
      %th Strength
      %th Vitality
      %th

    - @characters.each do |character|
      %tr
        %td= character.id
        %td= character.name
        %td= character.strength
        %td= character.vitality
        %td= link_to "delete", character, method: :delete, confirm: 'Delete?'

%p
  = link_to "Create a new Character", new_character_path, class: 'btn btn-primary'

app/views/characters/new.haml
= form_for @character do |f|
  %p
    Name
    = f.text_field :name
  %p
    Strength
    = f.text_field :strength
  %p
    Vitality
    = f.text_field :vitality
  %p
    = f.submit "Save"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MmoirpgServer</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class='container'>
  <div class='col-md-3'>
    <%= render 'shared/sidenav' %>
  </div>

  <div class='col-md-9'>
    <%= yield %>
  </div>
<div>

</body>
</html>

app/views/shared/_sidenav.haml
%h1 MMOIRPG
%ul.nav.nav-pills.nav-stacked
  %li= link_to "Characters", characters_path
  %li= link_to "Battles", battles_path
  %li
  %li
  %li=link_to "Log out"